apiVersion: v1
kind: Service
metadata:
  name: mynodeport
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 3000
  # which pods to route to
  # will randomly distribute traffic across all matching pods
  selector:
    # tags
    app: myapp